# Generated by Django 5.0.2 on 2024-07-16 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weightGoal", models.FloatField()),
                ("duration", models.IntegerField()),
                ("selectedGoals", models.JSONField()),
                ("description", models.TextField()),
                ("consultation_is_needed", models.BooleanField(default=False)),
                ("consultation_interval", models.IntegerField(blank=True, null=True)),
                (
                    "consultation_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("weeks", "Weeks"),
                            ("days", "Days"),
                            ("months", "Months"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("reps", models.IntegerField()),
                ("sets", models.IntegerField()),
                (
                    "diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="diet.diet",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("description", models.TextField()),
                (
                    "diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="diet.diet",
                    ),
                ),
            ],
        ),
    ]
