# Generated by Django 5.0.2 on 2024-07-16 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diet",
            old_name="selectedGoals",
            new_name="selected_goals",
        ),
        migrations.RenameField(
            model_name="diet",
            old_name="weightGoal",
            new_name="weight_goal",
        ),
    ]
