# Generated by Django 5.0.2 on 2024-07-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0002_rename_selectedgoals_diet_selected_goals_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diet",
            name="selected_goals",
            field=models.JSONField(default=list),
        ),
    ]
