# Generated by Django 5.0.2 on 2024-07-16 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0003_alter_diet_selected_goals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diet",
            name="selected_goals",
        ),
        migrations.CreateModel(
            name="SuggestedGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal", models.CharField(max_length=255)),
                (
                    "diet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suggested_goals",
                        to="diet.diet",
                    ),
                ),
            ],
        ),
    ]
