# Generated by Django 5.0.2 on 2024-07-16 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0004_remove_diet_selected_goals_suggestedgoal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diet",
            name="consultation_is_needed",
        ),
    ]
