# Generated by Django 5.0.2 on 2024-07-16 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diet", "0005_remove_diet_consultation_is_needed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
