# Generated by Django 5.0.2 on 2024-07-16 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor", "0003_alter_doctordetails_doctor_name"),
        ("patientInfo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ap_date", models.DateField()),
                ("ap_start_time", models.TimeField()),
                ("ap_end_time", models.TimeField()),
                (
                    "ap_type",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=7,
                    ),
                ),
                ("google_meet_link", models.URLField(blank=True, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="doctor.doctordetails",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patientInfo.patienthealthrecord",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                fields=("doctor", "patient", "ap_date", "ap_start_time"),
                name="unique_appointment",
            ),
        ),
    ]
