# Generated by Django 5.0.2 on 2024-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="room_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="ap_type",
            field=models.CharField(
                choices=[("online", "Online"), ("physical", "Physical")], max_length=10
            ),
        ),
    ]
