# Generated by Django 5.0.2 on 2024-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0002_appointment_room_number_alter_appointment_ap_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="description",
            field=models.TextField(default="hhms"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="title",
            field=models.CharField(default="hhms", max_length=255),
        ),
    ]
