# Generated by Django 5.0.2 on 2024-07-16 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0003_appointment_description_appointment_title"),
        ("patientInfo", "0002_alter_patienthealthrecord_p_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="description",
            field=models.TextField(default="Appointment details"),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="patientInfo.patienthealthrecord",
                to_field="p_user_id",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="title",
            field=models.CharField(default="Check-up", max_length=255),
        ),
    ]
