# Generated by Django 5.0.2 on 2024-07-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0004_alter_appointment_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="missed",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
