# Generated by Django 5.0.2 on 2024-07-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0005_appointment_completed_appointment_missed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="google_meet_link",
            field=models.CharField(default="www.youtube.com", max_length=255),
        ),
    ]
