# Generated by Django 5.0.2 on 2024-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointment", "0006_alter_appointment_google_meet_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="google_meet_link",
            field=models.CharField(
                blank=True, default="www.youtube.com", max_length=255
            ),
        ),
    ]
