# Generated by Django 5.0.7 on 2024-07-14 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HHMSUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("f_name", models.CharField(max_length=10)),
                ("l_name", models.CharField(max_length=10)),
                ("contact_number", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=10)),
                ("district", models.CharField(max_length=10)),
                ("division", models.CharField(max_length=10)),
                ("date_of_birth", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("doctor", "Doctor"),
                            ("patient", "Patient"),
                            ("admin", "Admin"),
                            ("manager", "Manager"),
                        ],
                        max_length=10,
                    ),
                ),
                ("user_status", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HHMSUserDoctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=15)),
                ("years_of_experience", models.IntegerField()),
                ("daily_hours", models.IntegerField()),
                ("room_number", models.IntegerField()),
                (
                    "doc_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authUser.hhmsuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HHMSUserDoctorSpecialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("specialization", models.CharField(max_length=10)),
                (
                    "doc_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authUser.hhmsuserdoctor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HHMSUserPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pat_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authUser.hhmsuser",
                    ),
                ),
            ],
        ),
    ]
