# Generated by Django 5.0.7 on 2024-07-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authUser", "0002_alter_hhmsuser_options_alter_hhmsuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hhmsuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="hhmsuser",
            name="user_status",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
