# Generated by Django 5.0.7 on 2024-07-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authUser", "0003_alter_hhmsuser_email_alter_hhmsuser_user_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hhmsuser",
            name="date_of_birth",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
