# Generated by Django 5.0.7 on 2024-07-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authUser", "0004_alter_hhmsuser_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hhmsuser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="hhmsuser",
            name="district",
        ),
        migrations.RemoveField(
            model_name="hhmsuser",
            name="division",
        ),
        migrations.AddField(
            model_name="hhmsuser",
            name="address",
            field=models.CharField(blank="True", max_length=255),
        ),
        migrations.AddField(
            model_name="hhmsuser",
            name="latitude",
            field=models.CharField(blank="True", max_length=255),
        ),
        migrations.AddField(
            model_name="hhmsuser",
            name="longitude",
            field=models.CharField(blank="True", max_length=255),
        ),
        migrations.AlterField(
            model_name="hhmsuser",
            name="contact_number",
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name="hhmsuser",
            name="type",
            field=models.CharField(
                choices=[
                    ("doctor", "Doctor"),
                    ("patient", "Patient"),
                    ("manager", "Manager"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="hhmsuser",
            name="user_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
