# Generated by Django 5.0.7 on 2024-07-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authUser", "0006_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(default="django.utils.timezone.now"),
        ),
    ]
