# Generated by Django 5.0.7 on 2024-07-16 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patientInfo", "0002_patienthealthrecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patienthealthrecord",
            name="blood_pressure",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="patienthealthrecord",
            name="date",
            field=models.DateTimeField(),
        ),
    ]
