# Generated by Django 5.0.7 on 2024-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patientInfo", "0004_diagnosisreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="diagnosisreport",
            name="user",
        ),
        migrations.AddField(
            model_name="diagnosisreport",
            name="user_id",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="diagnosisreport",
            name="file",
            field=models.CharField(max_length=255),
        ),
    ]
