# Generated by Django 5.0.2 on 2024-07-14 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorDetails",
            fields=[
                (
                    "doc_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("department", models.CharField(max_length=15)),
                ("years_of_experience", models.IntegerField()),
                ("daily_hours", models.IntegerField()),
                ("room_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="DoctorSpecialization",
            fields=[
                (
                    "doc_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("Cardiology", "Cardiology"),
                            ("Neurology", "Neurology"),
                            ("Pediatrics", "Pediatrics"),
                            ("General Surgery", "General Surgery"),
                            ("Orthopedics", "Orthopedics"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
