# Generated by Django 5.0.2 on 2024-07-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctordetails",
            name="doctor_name",
            field=models.CharField(
                default="John Doe", max_length=50, verbose_name="John Doe"
            ),
        ),
    ]
