# Generated by Django 5.0.2 on 2024-07-14 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0002_doctordetails_doctor_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctordetails",
            name="doctor_name",
            field=models.CharField(default="John Doe", max_length=50),
        ),
    ]
